services:
  - type: web # Servicio del Procesador de Datos
    name: data-processor
    env: docker
    repo: https://github.com/jsvalencia/i4 # <-- THIS NEEDS TO BE YOUR ACTUAL REPO URL
    rootDir: ./data_processor
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      # PORT is automatically assigned by Render.
  - type: web # Servicio del Recolector de Sensores
    name: sensor-collector
    env: docker
    repo: https://github.com/jsvalencia/i4 # <-- THIS NEEDS TO BE YOUR ACTUAL REPO URL
    rootDir: ./sensor_collector
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATA_PROCESSOR_URL
        value: https://data-processor-v27b.onrender.com/api/data # Or your internal service address if preferred
      # PORT is automatically assigned by Render.